spring.application.name=twitter-api
server.port=3000

# Veritaban? Ba?lant? Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate Ayarlar? (Tablolar?n otomatik olu?mas? için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect